### ISSUE TITLE
Any way you support hkp:// for keys?

### ISSUE THREAD

**Issue by EugenMayer** [manala/ansible-role-apt#8]
URLs for keys, like hkp://p80.pool.sks-keyservers.net:80 are common, e.g in https://docs.docker.com/engine/installation/linux/debian/

is there any way you could support that?

Thank you

**Comment by nervo** [comment]
Sure, we already support it in some of our pattern keys.
Have a look on this: https://github.com/manala/ansible-role-apt/blob/master/vars/main.yml#L193

In general, we prefer having pattern keys instead of defining them manually. This way, we could handle changes, uploads, etc...

Could you show us your usage ?

**Comment by EugenMayer** [comment]
Just try to define a statement to include the key referenced in for the docker repo.

Nevertheless, i backed of from ansible, back to chef - sorry, will not really contribute here too much.

**Comment by nervo** [comment]
We already have a docker key pattern: https://github.com/manala/ansible-role-apt/blob/master/vars/main.yml#L207

Can we close ?

**Comment by EugenMayer** [comment]
Did not notice that, not testing it though ( small notice, they changed keys in the past, you should verify that really is the right key ). For you, sure close it

**Comment by nervo** [comment]
I've just checked the key, we're ok :)

Thanks for the info.
